AWSTemplateFormatVersion: "2010-09-09"                                                      
Description: "Laboratorio 3"                                                                
Resources:                                                                                  
    Ec2Instance:                                                                            
        Type: AWS::EC2::Instance                                                            
        Properties:                                                                        
            DisableApiTermination: true                                                    
            ImageId: ami-041feb57c611358bd                                                  
            InstanceType: t2.micro                                                          
            SubnetId: subnet-0dfd796599a71e659                                              
            SecurityGroupIds:                                                              
                - !Ref SecurityGroup                                                        
            Tags:                                                                          
                - Key: Name                                                                
                  Value: Web-Server                                                        
            UserData:                                                                      
                Fn::Base64: |                                                              
                    #!/bin/bash                                                            
                    dnf install -y httpd                                                    
                    systemctl enable httpd                                                  
                    systemctl start httpd                                                  
                    echo '<html><h1>SUUUUUUUUUUUUUUU!!</h1></html>' > /var/www/html/index.html                                                                                      
    SecurityGroup:                                                                          
        Type: AWS::EC2::SecurityGroup                                                      
        Properties:                                                                        
            GroupDescription: "Security group for my web server"                            
            GroupName: "Web server security group"                                          
            SecurityGroupIngress:                                                          
                - IpProtocol: tcp                                                          
                  FromPort: 80                                                              
                  ToPort: 80                                                                
                  CidrIp: "0.0.0.0/0"                                                      
            VpcId: vpc-05e264a87974a205b
